version: 2.1

jobs:
  test:
    docker:
      - image: navarasan0112/flask-supabase-app:latest
    steps:
      - checkout
      - run:
          name: ✅ Run tests
          command: pytest test_app.py

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: 🚀 Trigger Render Deployment
          command: |
            curl -X POST "https://api.render.com/deploy/srv-d1g3iv6mcj7s73cbbpbg?key=dc2XbOXGkfE"
      - run:
          name: 📣 Notify Sleuth of Deployment
          command: |
            curl -X POST "https://app.sleuth.io/api/1/deployments" \
              -H "Authorization: Bearer $SLEUTH_API_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "project": "your-sleuth-project",
                "environment": "production",
                "deployable": {
                  "sha": "'"$CIRCLE_SHA1"'",
                  "reference": "'"$CIRCLE_BRANCH"'"
                },
                "metadata": {
                  "deployed_by": "'"$CIRCLE_USERNAME"'"
                }
              }'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
