version: 2.1

jobs:
  test:
    docker:
      - image: navarasan0112/flask-supabase-app

    steps:
      - checkout

      - run:
          name: ✅ Run tests
          command: pytest test_app.py

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
